# Generated by Django 5.1.5 on 2025-01-26 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttb',
            name='cat_id',
        ),
        migrations.AddField(
            model_name='producttb',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.categorytb'),
            preserve_default=False,
        ),
    ]
