# Generated by Django 5.1.5 on 2025-01-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_producttb_cat_id_producttb_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttb',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
